### ISSUE TITLE
ImportError: No module named 'hashtype'

### ISSUE THREAD

**Issue by reubano** [sean-public/python-hashes#5]
Python 3.5.2

```bash
Traceback (most recent call last):
  File "gcontact/__init__.py", line 32, in <module>
    from hashes.simhash import simhash as Simhash
  File "/Users/reubano/.virtualenvs/contacts/lib/python3.5/site-packages/hashes/simhash.py", line 10, in <module>
    from hashtype import hashtype
ImportError: No module named 'hashtype'
```

**Comment by reubano** [comment]
Quick fix... thanks! Btw, I've started a [fork](https://github.com/reubano/changanya) you may want to take a look at. It breaks few things since it is Python 3+. But let me know if there is anything worth porting that you'd like me to submit PRs for.

**Comment by sean-public** [comment]
Thank you for reporting that issue, glad to fix it!

However, because of the MIT license, you are free to fork, use, modify, sell, etc. the software as you please. However, it also specifies:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

You changed the copyright in [this commit](https://github.com/reubano/changanya/commit/32c6228cf3cbe192e58476e97a349d997cb58187), which I now ask you to change back. You can copyright your changes and license them as you wish, but must persist the original copyright and license along with your new one.
